#:schema node_modules/wrangler/config-schema.json
name = "database"
main = "src/index.ts"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

services = [{ binding = "STORAGE", service = "storage" }]

[[d1_databases]]
binding = "DB"
database_name = "d1-virtualbox"
database_id = "d0ce18e5-243e-4c53-9164-4613bfb66b43"

